### PR TITLE
Package project, so it can be installed via pip

### PR DESCRIPTION
**Pull request by g-braeunlich**
See https://kivy.org/doc/stable/api-kivy.garden.html

### CODE REVIEW

**Review by Joshua-Douglas — CHANGES_REQUESTED** [review]
Hey @g-braeunlich,

Great change. I especially appreciate the `MathTextParser` fix, that's been bugging me and I almost submitted a PR myself.

Doing a pip install would be a lot easier than relying on the legacy flower format.
I tried out the `toml` file and it worked on my machine, with a warning.  

The only problem is that I think this approach breaks the [guidance outlined in the kivy garden docs](https://kivy-garden.github.io/#guideformigratingflowersfromlegacystructure). The docs state that repos must be archived when upgrading the flower format. 

I don't know the exact reasoning behind this rule, but it might have to do with the ambiguous absolute import. If this flower is installed using the legacy format then the import statement is `kivy.garden.matplotlib`. If the flower is installed using `pip` then the import statement is `kivy_garden.matplotlib`.

If one of the maintainers approves this approach, then I have a one more comment:
* The example `py` files are now broken. You'll need to fix the import statements for them to work with pip.

**Comment by g-braeunlich** [comment]
Thanks a lot for your comments. In this case, I am going to request a new repo and will attempt to migrate it there properly.

**Comment by g-braeunlich** [comment]
Request submitted here: https://github.com/kivy-garden/kivy-garden.github.io/issues/162

**Comment by g-braeunlich** [comment]
Also updated my commits, so the examples work

**Comment by misl6** [comment]
Hi @g-braeunlich !

Thank you for the friendly ping about this one.
I'm starting the migration, and the new repo will be available in a while.

Can you please consider proposing the changes again when the new repo is ready?

**Comment by tcaduser** [comment]
Hi @g-braeunlich,

Please let me know if your PR addresses my Issue kivy-garden/matplotlib#1, which finds a breaking change for matplotlib 3.8.0.  Please note that kivy-ios uses matplotlib 3.7.2 and android uses 3.5.2.

**Comment by misl6** [comment]
@g-braeunlich , @Joshua-Douglas , @tcaduser :

The matplotlib flower has been moved to https://github.com/kivy-garden/matplotlib .
We do not have a release yet, and tests need to be implemented, but at least is a starting point.

(I will slowly move all the still valid issues to the new repo, ASAP)

Feel free to submit your PRs from now on.

**Comment by g-braeunlich** [comment]
> Hi @g-braeunlich,
> 
> Please let me know if your PR addresses my Issue [kivy-garden/matplotlib#1](https://github.com/kivy-garden/matplotlib/issues/1), which finds a breaking change for matplotlib 3.8.0. Please note that kivy-ios uses matplotlib 3.7.2 and android uses 3.5.2.

@tcaduser My PR does not address your issue. However chances are that my colleague solved that issue.
I will ask him on Monday

**Pull request closed without merging**
