### PR TITLE
pos bound to the widget, needed for layouts.

### PR DESCRIPTION
**Pull request by andnovar**

### CODE REVIEW

**Comment by dessant** [comment]
@andnovar, wouldn't redrawing on every pos change be wasteful?

**Comment by matham** [comment]
Yes, we need to rework that so a resize or re-position defers a update until the end of the frame. Because updating at every resize or re-position is too expensive.

**Comment by dessant** [comment]
@matham, on pos change, an update means repositioning only, not grabbing the texture again from mpl, right?

**Comment by matham** [comment]
Not for the kivy backend because everything needs to be redrawn since all the meshes etc will need to be moved.

**Comment by andnovar** [comment]
I think for pos redrawing can be avoided and a transformation can be applied to just translate the texture, but for resizing is harder because matplotlib needs to recalculate positions and redraw elements based on size.

**Comment by matham** [comment]
Why are there unrelated changes in this pr? There should only be changes relating to pos. Anything else needs to be in its own PR.

**Comment by andnovar** [comment]
https://github.com/kivy-garden/garden.matplotlib/pull/14

**Pull request closed without merging**
